env:
  browser: true
  jquery: true
  es6: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:jest/recommended
parserOptions:
  ecmaVersion: 2017
  ecmaFeatures:
    jsx: true
    experimentalObjectRestSpread: true
  sourceType: module
plugins:
  - jest
  - react
rules:
  comma-style:
    - error
    - first
  key-spacing:
    - error
    - align:
        on: colon
        beforeColon: true
        afterColon: true
  no-await-in-loop:
    - error
  no-template-curly-in-string:
    - error
  array-bracket-spacing:
    - 2
    - never
  indent:
    - off
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-console: 0
